### ISSUE TITLE
Reduce Duplicate Entries

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#60] opened 2017-10-10 13:24 UTC
per Meghan UX

Some way to reduce duplicate entries (stop them from getting made), which probably means seeing some details about other entries. Like - we've received other requests from that general area, could these be the same? - type of queries.

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507588260000280?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by ArtOfCode-** [comment] 2017-10-10 13:42
Duplicate of #47

**Closed by ArtOfCode-** 2017-10-10 13:42 UTC
