### ISSUE TITLE
Edit logging improvements with suggested edits

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/CrowdRescue#30] opened 2017-09-23 03:15 UTC
We should stop using case notes for edit tracking and instead use self-approved suggested edits. Those should then be listed with the case notes for each rescue request. This can't be started until #29 is merged.

This should also work in conjunction with #31 in that it should say "UserXXX edited _(edit approved by userXXX)_" and that should link to the suggested edit review.

**Comment by ArtOfCode-** [comment] 2017-09-27 17:49
Duplicate of #18 

(okay maybe not *entirely*, but having one issue for the topic will help us track them more effectively)

**Closed by ArtOfCode-** 2017-09-27 17:49 UTC
Labels: enhancement
